server:
  port: 80

spring:
  jpa:
    # 应用启动时是否自动建表，默认为false
    generate-ddl: true
    # 在控制台显示sql语句
    show-sql: true
    # 应用启动时不重新建表
    hibernate:
      ddl-auto: none
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://129.28.74.161/vickking?useUnicode=true&characterEncoding=UTF-8
    username: vickking
    password: vickking
    driver-class-name: com.mysql.jdbc.Driver